### ISSUE TITLE
Errors while running dev

### ISSUE THREAD

**Issue by timotius02** [OrJDev/trpc-limiter#4]
Running into these errors when trying to initially setup the project locally. These are the logs from @trpc-limiter/solid but the same error message also occurs with @trpc-limiter/next. 

```
@trpc-limiter/solid:dev: src/index.ts(5,8): error TS7016: Could not find a declaration file for module '@trpc-limiter/core'. '/home/timotius02/trpc-limiter/packages/core/dist/index.js' implicitly has an 'any' type.
@trpc-limiter/solid:dev:   Try `npm i --save-dev @types/trpc-limiter__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@trpc-limiter/core';`
@trpc-limiter/solid:dev: src/index.ts(9,31): error TS7006: Parameter 'req' implicitly has an 'any' type.
@trpc-limiter/solid:dev: src/index.ts(10,6): error TS7006: Parameter 'name' implicitly has an 'any' type.
@trpc-limiter/solid:dev: src/index.ts(10,12): error TS7006: Parameter 'value' implicitly has an 'any' type.
@trpc-limiter/solid:dev: 
@trpc-limiter/solid:dev: Error: error occured in dts build
@trpc-limiter/solid:dev:     at Worker.<anonymous> (/home/timotius02/trpc-limiter/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.4/node_modules/tsup/dist/index.js:2226:26)
@trpc-limiter/solid:dev:     at Worker.emit (node:events:526:28)
@trpc-limiter/solid:dev:     at MessagePort.<anonymous> (node:internal/worker:232:53)
@trpc-limiter/solid:dev:     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
@trpc-limiter/solid:dev:     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
@trpc-limiter/solid:dev: DTS Build failed
@trpc-limiter/solid:dev: RollupError: Failed to compile. Check the logs above.
@trpc-limiter/solid:dev:     at error (/home/timotius02/trpc-limiter/node_modules/.pnpm/rollup@3.9.1/node_modules/rollup/dist/shared/rollup.js:210:30)
@trpc-limiter/solid:dev:     at Object.error (/home/timotius02/trpc-limiter/node_modules/.pnpm/rollup@3.9.1/node_modules/rollup/dist/shared/rollup.js:23975:20)
@trpc-limiter/solid:dev:     at Object.error (/home/timotius02/trpc-limiter/node_modules/.pnpm/rollup@3.9.1/node_modules/rollup/dist/shared/rollup.js:23220:42)
@trpc-limiter/solid:dev:     at Object.transform (/home/timotius02/trpc-limiter/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.4/node_modules/tsup/dist/rollup.js:7287:20)
@trpc-limiter/solid:dev:     at /home/timotius02/trpc-limiter/node_modules/.pnpm/rollup@3.9.1/node_modules/rollup/dist/shared/rollup.js:24176:40

```

Not sure if I'm doing something wrong on my end when setting this up but I have tried resetting the project a couple times.

**Comment by OrJDev** [comment]
go to the root of the project

run 

```bash
pnpm build
```

then run this:

```bash
cd examples/solidstart && pnpm dev
```
